// Base UI Components（core 共享原子组件，P1 Step 4 自 uikit-im 迁入）
// 对外统一使用 Em 前缀，避免与业务方组件命名冲突
export { default as EmButton } from './button/button.vue'
export { default as EmIconButton } from './icon-button/icon-button.vue'
export { default as EmAvatar } from './avatar/avatar.vue'
export { default as EmBadge } from './badge/badge.vue'
export { default as EmIcon } from './icon/icon.vue'
export { default as EmInput } from './input/input.vue'
export { default as EmPopup } from './popup/popup.vue'
export { default as EmModal } from './modal/modal.vue'
export { default as EmToast } from './toast/toast.vue'
export { default as EmActionSheet } from './action-sheet/action-sheet.vue'
export type { ActionSheetItem } from './action-sheet/action-sheet.vue'
export { default as EmScrollToTop } from './scroll-to-top/scroll-to-top.vue'
export { default as EmEmojiPicker } from './emoji-picker/emoji-picker.vue'
export type { EmojiStickerItem, EmojiStickerPack } from './emoji-picker/types'
export { default as EmUserCard } from './user-card/user-card.vue'
export type { UserCardAction, UserCardInfoRow } from './user-card/user-card.vue'
export { default as EmPresenceSelector } from './presence-selector/presence-selector.vue'
export { default as EmPresenceSelectorModal } from './presence-selector/presence-selector-modal.vue'
export { default as EmPresenceSelectorPopup } from './presence-selector/presence-selector-popup.vue'
export { default as EmPresenceAvatar } from './presence-avatar/presence-avatar.vue'
export { default as EmCell } from './cell/cell.vue'
export type { CellProps } from './cell/cell.vue'
export { default as EmCopyableText } from './copyable-text/copyable-text.vue'
export type { CopyableTextProps } from './copyable-text/copyable-text.vue'
export { default as EmEmpty } from './empty/empty.vue'
export type { EmptyProps } from './empty/empty.vue'
export { default as EmNotification } from './notification/notification.vue'
export type { NotificationProps } from './notification/notification.vue'
export { default as EmNotificationContainer } from './notification/notification-container.vue'
export type { NotificationContainerProps } from './notification/notification-container.vue'
export type { NotificationItem } from './notification/types'
export { default as EmStatusBanner } from './status-banner/status-banner.vue'
export type { StatusBannerProps, StatusBannerEmits } from './status-banner/status-banner.vue'
export type { StatusBannerType, StatusBannerItem } from './status-banner/types'
export { default as EmImageViewer } from './image-viewer/image-viewer.vue'
export type { ImageViewerProps, ImageViewerEmits } from './image-viewer/image-viewer.vue'
export { default as EmResizable } from './resizable/resizable.vue'
export type { ResizableProps } from './resizable/resizable.vue'
export type { PresenceDisplayStatus } from './avatar/avatar.vue'
