/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DemoDanmakuStage: typeof import('./src/components/demo-danmaku-stage.vue')['default']
    DemoLiveProductCard: typeof import('./src/components/demo-live-product-card.vue')['default']
    DemoSceneHeader: typeof import('./src/components/demo-scene-header.vue')['default']
  }
}
