export const EasemobUIKitImports = {
  '@easemob/uikit': [
    'useUIKit',
    'useChat',
    'useConversation',
    'useConversationTabs',
    'useMessage',
    'useContact',
    'useGroup',
    'useClient',
    'useTheme',
    'useH5Adaptation',
    'useKeyboard',
    'useLongPress',
    'useViewport',
    'useToast',
    'useNotification',
    'useLocale',
    'usePresence',
    'useBlocklist',
    'useUserInfo',
    'useOwnUserInfo',
    'useBottomSheet',
  ],
}
