// Base UI Components
// 对外统一使用 Em 前缀，避免与业务方组件命名冲突
// P1 Step 4：原子组件已迁入 @easemob/uikit-core，此处显式具名 re-export 保持对外 API 不变
export {
  EmActionSheet,
  EmAvatar,
  EmBadge,
  EmButton,
  EmCell,
  EmCopyableText,
  EmEmojiPicker,
  EmEmpty,
  EmIcon,
  EmIconButton,
  EmImageViewer,
  EmInput,
  EmModal,
  EmNotification,
  EmNotificationContainer,
  EmPopup,
  EmPresenceAvatar,
  EmPresenceSelector,
  EmPresenceSelectorModal,
  EmPresenceSelectorPopup,
  EmResizable,
  EmScrollToTop,
  EmSkeleton,
  EmStatusBanner,
  EmToast,
  EmUserCard,
} from '@easemob/uikit-core'
export type {
  CellProps,
  CopyableTextProps,
  EmojiStickerItem,
  EmojiStickerPack,
  EmptyProps,
  ImageViewerEmits,
  ImageViewerProps,
  NotificationContainerProps,
  NotificationItem,
  NotificationProps,
  PresenceDisplayStatus,
  ResizableProps,
  SkeletonProps,
  StatusBannerEmits,
  StatusBannerItem,
  StatusBannerProps,
  StatusBannerType,
} from '@easemob/uikit-core'
export { default as EmUserCardModal } from './user-card/user-card-modal.vue'
export { default as EmGroupCard } from './group-card/group-card.vue'
export { default as EmGroupCardModal } from './group-card/group-card-modal.vue'

export const componentList = [
  'em-button',
  'em-icon-button',
  'em-avatar',
  'em-badge',
  'em-icon',
  'em-input',
  'em-popup',
  'em-modal',
  'em-toast',
  'em-action-sheet',
  'em-scroll-to-top',
  'em-emoji-picker',
  'em-user-card',
  'em-user-card-modal',
  'em-group-card',
  'em-group-card-modal',
  'em-presence-selector',
  'em-presence-selector-modal',
  'em-presence-selector-popup',
  'em-presence-avatar',
  'em-cell',
  'em-copyable-text',
  'em-empty',
  'em-notification',
  'em-notification-container',
  'em-status-banner',
  'em-image-viewer',
  'em-resizable',
  'em-skeleton',
] as const
