/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DemoSettingGroup: typeof import('./src/components/demo-setting-group.vue')['default']
    NavSidebar: typeof import('./src/components/nav-sidebar.vue')['default']
  }
}
