/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DemoAppearancePanel: typeof import('./src/components/settings/demo-appearance-panel.vue')['default']
    DemoCardMessage: typeof import('./src/components/demo-card-message.vue')['default']
    DemoCardPickerModal: typeof import('./src/components/demo-card-picker-modal.vue')['default']
    DemoChatPanel: typeof import('./src/components/settings/demo-chat-panel.vue')['default']
    DemoContactPanel: typeof import('./src/components/settings/demo-contact-panel.vue')['default']
    DemoConversationPanel: typeof import('./src/components/settings/demo-conversation-panel.vue')['default']
    DemoDataPanel: typeof import('./src/components/settings/demo-data-panel.vue')['default']
    DemoDeveloperPanel: typeof import('./src/components/settings/demo-developer-panel.vue')['default']
    DemoNotificationPanel: typeof import('./src/components/settings/demo-notification-panel.vue')['default']
    DemoProviderPanel: typeof import('./src/components/settings/demo-provider-panel.vue')['default']
    DemoQuickReplyPanel: typeof import('./src/components/demo-quick-reply-panel.vue')['default']
    DemoSdkPanel: typeof import('./src/components/settings/demo-sdk-panel.vue')['default']
    DemoSettingLabel: typeof import('./src/components/settings/demo-setting-label.vue')['default']
    DemoSettingsDrawer: typeof import('./src/components/settings/demo-settings-drawer.vue')['default']
    NavSidebar: typeof import('./src/components/nav-sidebar.vue')['default']
  }
}
